### ISSUE TITLE
小学生並みの感想

### ISSUE THREAD

**Issue by mogamoga1024** [lovecall6700/Game2#1]
（v3.5.5）
裏技あり、マップカンニングありでプレイしたら楽しめました。またBGMもよかったです。
~~裏技時、画面外で高くジャンプして死亡するのが少々苦痛でした。~~

自力でクリアしたら後世まで誇っていいと思います。

**Comment by lovecall6700** [comment]
ありがとうございます。超急ぐと通常ルートは1分かからずにクリアできます。
